### ISSUE TITLE
Access research grant data

### ISSUE THREAD

**Issue by beingkk** [nestauk/innovation_sweet_spots#3]
- [x] Set up data access configs
- [x] Use `data_getters` to access GtR data. 
- [x] Write a small script that builds the project table with the relevant fields.
- [x] Write and document functions and tests

**Comment by beingkk** [comment]
Got an error when trying to build a project table in the following way
```python
from data_getters.gtr import build_projects
import pandas as pd
config_path = "path-to-config/mysqldb_team.config"
fields = ["id", "title", "start", "end", "abstractText", "techAbstractText"]
projects = build_projects(
    config_path,
    chunksize=1000,
    table_wildcards=["gtr_projects"],
    desired_fields=fields)
df = pd.DataFrame(projects)
dt.to_csv('gtr_projects.csv')
```
The returned error:
```python
Traceback (most recent call last):
  File "innovation_sweet_spots/getters/gtr.py", line 16, in <module>
    desired_fields=["id", "title", "start", "end", "abstractText", "techAbstractText"])
  File "/Users/karliskanders/opt/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/data_getters/gtr.py", line 93, in build_projects
    out_data = list(map(deduplicate, projects.values()))
  File "/Users/karliskanders/opt/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages/data_getters/gtr.py", line 38, in deduplicate
    value = '\n'.join(tuple(set(value)))
TypeError: sequence item 0: expected str instance, datetime.datetime found

```

**Comment by beingkk** [comment]
By specifying the fields simply as `fields = ["id", "title"]` or `fields = ["id"]` the above script worked, and returned a dataframe with the following columns

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118730 entries, 0 to 118729
Data columns (total 15 columns):
Unnamed: 0                    118730 non-null int64
abstractText                  117236 non-null object
created                       106975 non-null object
end                           11753 non-null object
grantCategory                 118729 non-null object
id                            118730 non-null object
leadFunder                    118730 non-null object
leadOrganisationDepartment    80781 non-null object
potentialImpact               30893 non-null object
projects_id                   24191 non-null object
projects_title                19995 non-null object
start                         11754 non-null object
status                        118730 non-null object
techAbstractText              17703 non-null object
title                         118730 non-null object
dtypes: int64(1), object(14)
memory usage: 13.6+ MB
```
