### ISSUE TITLE
Error in conda environment setup for M1 Mac machines

### ISSUE THREAD

**Issue by dede95** [nestauk/innovation_sweet_spots#39]
Error in setting up a conda environment when running `make install` on an M1 Mac machine. 

Example of error is [documented here](https://docs.google.com/document/d/1VNBRiNMLHsGXQfvEMwFh5-5fnNWJs2MSFe7lWb76Y-g/edit).

**Comment by mathickman** [comment]
I'm getting a similar problem, also on a fresh M1 Mac: `make install` doesn't work, but I'm getting a different error. There seem to be [some other discussions](https://github.com/Toblerity/Shapely/issues/1080) of this, but I can't get it to work.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/9505957/138473313-c0bb07e4-6c81-4391-936b-2ec682825408.png">

**Comment by mathickman** [comment]
Update: apologies for excessively long Terminal output, below, but for completeness. Per suggestion from @beingkk, I removed the `--quiet` tags from the `makefile`, which yields the following:

```
(iss) ➜  innovation_sweet_spots git:(29_public_discourse) make install                           
conda env create -q -n innovation_sweet_spots -f environment.yaml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 

done
/Library/Developer/CommandLineTools/usr/bin/make -s pip-install
Collecting data_getters@ git+https://github.com/nestauk/data_getters.git
  Cloning https://github.com/nestauk/data_getters.git to /private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/data-getters_4eb342de6dce4752b93bb5957b8306f5
  Running command git clone -q https://github.com/nestauk/data_getters.git /private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/data-getters_4eb342de6dce4752b93bb5957b8306f5
  Resolved https://github.com/nestauk/data_getters.git to commit 2a31d737a4d29fae3ad8617a25fbacc961d085d4
Collecting nesta@ git+git://github.com/nestauk/nesta.git@291_glass_ai#egg=nesta
  Cloning git://github.com/nestauk/nesta.git (to revision 291_glass_ai) to /private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/nesta_d6e9d884f6a24c3abf4e0b1abe35e522
  Running command git clone -q git://github.com/nestauk/nesta.git /private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/nesta_d6e9d884f6a24c3abf4e0b1abe35e522
  Running command git checkout -b 291_glass_ai --track origin/291_glass_ai
  Switched to a new branch '291_glass_ai'
  Branch '291_glass_ai' set up to track remote branch '291_glass_ai' from 'origin'.
  Resolved git://github.com/nestauk/nesta.git to commit 895b30a2a0e8c8b9cd4c9697274defbb7a60604b
Collecting alchemy_mock==0.4.1
  Using cached alchemy_mock-0.4.1-py2.py3-none-any.whl (13 kB)
Collecting alphabet_detector==0.0.7
  Using cached alphabet-detector-0.0.7.tar.gz (1.6 kB)
Collecting beautifulsoup4==4.8.0
  Using cached beautifulsoup4-4.8.0-py3-none-any.whl (97 kB)
Collecting boto3==1.9.159
  Using cached boto3-1.9.159-py2.py3-none-any.whl (128 kB)
Collecting botocore==1.12.205
  Using cached botocore-1.12.205-py2.py3-none-any.whl (5.7 MB)
Collecting corextopic==1.0.6
  Using cached corextopic-1.0.6-py3-none-any.whl (26 kB)
Collecting elasticsearch==6.4.0
  Using cached elasticsearch-6.4.0-py2.py3-none-any.whl (81 kB)
Collecting fuzzywuzzy==0.17.0
  Using cached fuzzywuzzy-0.17.0-py2.py3-none-any.whl (13 kB)
Collecting gensim==3.7.3
  Using cached gensim-3.7.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.7 MB)
Collecting geopy==1.20.0
  Using cached geopy-1.20.0-py2.py3-none-any.whl (100 kB)
Collecting googletrans==2.4.0
  Using cached googletrans-2.4.0.tar.gz (17 kB)
Collecting jellyfish==0.7.1
  Using cached jellyfish-0.7.1.tar.gz (131 kB)
Collecting luigi==2.8.6
  Using cached luigi-2.8.6.tar.gz (1.2 MB)
Collecting lxml==4.3.4
  Using cached lxml-4.3.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.7 MB)
Collecting matplotlib==3.1.1
  Using cached matplotlib-3.1.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.4 MB)
Collecting mock==3.0.5
  Using cached mock-3.0.5-py2.py3-none-any.whl (25 kB)
Collecting mysql_connector_repackaged==0.3.1
  Using cached mysql-connector-repackaged-0.3.1.tar.gz (132 kB)
Collecting nltk==3.4.5
  Using cached nltk-3.4.5.zip (1.5 MB)
Collecting nuts_finder==0.1.2
  Using cached nuts_finder-0.1.2.tar.gz (2.9 kB)
Collecting numpy==1.16.4
  Using cached numpy-1.16.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9 MB)
Collecting pairing==0.1.3
  Using cached pairing-0.1.3.zip (3.2 kB)
Collecting pandas==0.24.2
  Using cached pandas-0.24.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (15.9 MB)
Collecting py2neo==4.3.0
  Using cached py2neo-4.3.0.tar.gz (71 kB)
Collecting pycountry==18.12.8
  Using cached pycountry-18.12.8-py2.py3-none-any.whl (10.5 MB)
Collecting pycountry_convert==0.7.2
  Using cached pycountry_convert-0.7.2-py3-none-any.whl (13 kB)
Collecting PyMySQL==0.9.3
  Using cached PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
Collecting pyshp==2.1.0
  Using cached pyshp-2.1.0.tar.gz (215 kB)
Collecting pytest==4.6.0
  Using cached pytest-4.6.0-py2.py3-none-any.whl (229 kB)
Collecting PyVirtualDisplay==0.2.3
  Using cached PyVirtualDisplay-0.2.3-py2.py3-none-any.whl (15 kB)
Collecting pyyaml==5.3.1
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting requests==2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting requests_aws4auth==0.9
  Using cached requests_aws4auth-0.9-py2.py3-none-any.whl (54 kB)
Collecting retrying==1.3.3
  Using cached retrying-1.3.3.tar.gz (10 kB)
Collecting s3fs==0.2.1
  Using cached s3fs-0.2.1.tar.gz (46 kB)
Collecting schema==0.7.2
  Using cached schema-0.7.2-py2.py3-none-any.whl (16 kB)
Collecting scikit_learn==0.21.3
  Using cached scikit_learn-0.21.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (10.5 MB)
Collecting scipy==1.2.2
  Using cached scipy-1.2.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.3 MB)
Collecting selenium==3.141.0
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting sentencepiece==0.1.86
  Using cached sentencepiece-0.1.86-cp37-cp37m-macosx_10_6_x86_64.whl (1.1 MB)
Collecting setuptools==41.1.0
  Using cached setuptools-41.1.0-py2.py3-none-any.whl (576 kB)
Requirement already satisfied: six>=1.12.0 in /Users/mathickman/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages (from nesta@ git+git://github.com/nestauk/nesta.git@291_glass_ai#egg=nesta->data_getters@ git+https://github.com/nestauk/data_getters.git->-r requirements_data_getters.txt (line 1)) (1.16.0)
Collecting SPARQLWrapper==1.8.4
  Using cached SPARQLWrapper-1.8.4-py3-none-any.whl (27 kB)
Collecting SQLAlchemy==1.3.4
  Using cached SQLAlchemy-1.3.4.tar.gz (5.9 MB)
Collecting toolz==0.10.0
  Using cached toolz-0.10.0.tar.gz (49 kB)
Collecting urllib3==1.24.2
  Using cached urllib3-1.24.2-py2.py3-none-any.whl (131 kB)
Collecting soupsieve>=1.2
  Using cached soupsieve-2.2.1-py3-none-any.whl (33 kB)
Collecting s3transfer<0.3.0,>=0.2.0
  Using cached s3transfer-0.2.1-py2.py3-none-any.whl (70 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/mathickman/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages (from botocore==1.12.205->nesta@ git+git://github.com/nestauk/nesta.git@291_glass_ai#egg=nesta->data_getters@ git+https://github.com/nestauk/data_getters.git->-r requirements_data_getters.txt (line 1)) (2.8.2)
Collecting docutils<0.15,>=0.10
  Using cached docutils-0.14-py3-none-any.whl (543 kB)
Collecting smart-open>=1.7.0
  Using cached smart_open-5.2.1-py3-none-any.whl (58 kB)
Collecting geographiclib<2,>=1.49
  Using cached geographiclib-1.52-py3-none-any.whl (38 kB)
Collecting tornado<5,>=4.0
  Using cached tornado-4.5.3.tar.gz (484 kB)
Collecting python-daemon<2.2.0
  Using cached python_daemon-2.1.2-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: cycler>=0.10 in /Users/mathickman/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages (from matplotlib==3.1.1->nesta@ git+git://github.com/nestauk/nesta.git@291_glass_ai#egg=nesta->data_getters@ git+https://github.com/nestauk/data_getters.git->-r requirements_data_getters.txt (line 1)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/mathickman/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages (from matplotlib==3.1.1->nesta@ git+git://github.com/nestauk/nesta.git@291_glass_ai#egg=nesta->data_getters@ git+https://github.com/nestauk/data_getters.git->-r requirements_data_getters.txt (line 1)) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/mathickman/miniconda3/envs/innovation_sweet_spots/lib/python3.7/site-packages (from matplotlib==3.1.1->nesta@ git+git://github.com/nestauk/nesta.git@291_glass_ai#egg=nesta->data_getters@ git+https://github.com/nestauk/data_getters.git->-r requirements_data_getters.txt (line 1)) (2.4.7)
Collecting geojson==2.5.0
  Using cached geojson-2.5.0-py2.py3-none-any.whl (14 kB)
Collecting Shapely==1.6.2.post1
  Using cached Shapely-1.6.2.post1.tar.gz (221 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/mathickman/miniconda3/envs/innovation_sweet_spots/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/shapely_ce56831028aa452887525eb007743934/setup.py'"'"'; __file__='"'"'/private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/shapely_ce56831028aa452887525eb007743934/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-pip-egg-info-v3valuak
         cwd: /private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/shapely_ce56831028aa452887525eb007743934/
    Complete output (11 lines):
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/shapely_ce56831028aa452887525eb007743934/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/shapely_ce56831028aa452887525eb007743934/shapely/_buildcfg.py", line 185, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "/private/var/folders/j0/489lf4y13szbzlrqg0md54b00000gn/T/pip-install-lpvxgbfp/shapely_ce56831028aa452887525eb007743934/shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/60/c4/392aff1cb73f20d3cf4bb01a9eeb3eb5db7a167c094d69beca402b9a5846/Shapely-1.6.2.post1.tar.gz#sha256=07fba518e76b3276558f62a5829bdfa476f790cdef752383ccdc8c66b04b0899 (from https://pypi.org/simple/shapely/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nltk to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mysql-connector-repackaged to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mock to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of lxml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of luigi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jellyfish to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of googletrans to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of geopy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gensim to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of fuzzywuzzy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of elasticsearch to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of corextopic to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of botocore to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of beautifulsoup4 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of alphabet-detector to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of alchemy-mock to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of nesta to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of data-getters to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement Shapely==1.6.2.post1 (from nuts-finder) (from versions: 1.0a7, 1.0b1, 1.0b2, 1.0b3, 1.0b4, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.2b1, 1.2b2, 1.2b3, 1.2b4, 1.2b5, 1.2b6, 1.2b7, 1.2rc1, 1.2rc2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.2.19, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.6a1, 1.6a2, 1.6b1, 1.6b2, 1.6b3, 1.6b4, 1.6b5, 1.6.0, 1.6.1, 1.6.2, 1.6.2.post1, 1.6.3, 1.6.4, 1.6.4.post1, 1.6.4.post2, 1.7a1, 1.7a2, 1.7a3, 1.7b1, 1.7.0, 1.7.1, 1.8a1, 1.8a2, 1.8a3, 1.8rc1, 1.8rc2)
ERROR: No matching distribution found for Shapely==1.6.2.post1
make[1]: *** [pip-install] Error 1
make: *** [conda-create] Error 2
```
